import { useEffect } from 'react'
import LanguageSwitcher from '../components/LanguageSwitcher.jsx'
import MinimumFlangeDiagram from '../components/MinimumFlangeDiagram.jsx'
import { getEngineeringText } from '../languages/engineeringText.js'
import { getSiteUrl, setPageSEO, setStructuredData } from '../utils/seo.js'

const routePath = '/engineering/minimum-flange-length-guide'
const relatedTools = [
  ['pressBrakeCalculator', '/engineering-tools/press-brake-calculator'],
  ['materialDatabase', '/engineering-tools/material-database'],
  ['vDieSelectionTool', '/engineering-tools/v-die-selection'],
  ['insideRadiusGuide', '/engineering-tools/inside-radius-guide'],
  ['springbackDatabase', '/engineering-tools/springback-database'],
  ['springbackCompensationGuide', '/springback-compensation-guide'],
  ['bendAllowanceCalculator', '/engineering-tools/bend-allowance-calculator'],
  ['kFactorGuide', '/engineering/k-factor-guide'],
  ['bendDeductionGuide', '/engineering/bend-deduction-guide'],
  ['airBendingGuide', '/engineering-tools/air-bending-guide'],
  ['bottomingVsCoiningGuide', '/engineering-tools/bottoming-vs-coining-guide'],
  ['pressBrakeTonnageGuide', '/engineering/press-brake-tonnage-guide'],
  ['vDieOpeningGuide', '/engineering/how-to-choose-press-brake-v-die-opening'],
  ['minimumFlangeLengthGuide', routePath],
  ['toolingSelectionGuide', '/engineering/press-brake-tooling-selection-guide'],
  ['crowningGuide', '/engineering/press-brake-crowning-guide'],
  ['stainlessSteelBendingGuide', '/engineering/stainless-steel-bending-guide'],
  ['aluminumBendingGuide', '/engineering/aluminum-bending-guide'],
]

const content = {
  en: {
    back: '← Back to Engineering Tools', eyebrow: 'Engineering Guide', title: 'Minimum Flange Length Guide',
    subtitle: 'Professional guide for understanding minimum flange length in press brake bending, V-die support, short flange stability and tooling selection.',
    seoDescription: 'Engineering guide to minimum flange length in press brake bending: V die opening, die shoulder support, short flange stability, radius, material and tooling solutions.',
    keywords: 'minimum flange length, press brake minimum flange, short flange bending, V die opening minimum flange, press brake flange length, short flange press brake, die shoulder support, minimum bend flange',
    what: { title: 'What Is Minimum Flange Length?', text: 'Minimum flange length is the shortest bend leg that can remain reliably seated on the lower-die shoulders while the punch starts and completes a bend. It is not only a drawing dimension. V opening, inside radius, sheet thickness, bending method and tooling shape determine whether the flange has enough support. When a short edge loses shoulder contact, it can fall into the V opening, shift the bend line or produce an unstable angle.' },
    why: { title: 'Why Minimum Flange Length Matters', cards: [['Short flange instability', 'A small leg can rotate or slide before the bend is established.'], ['Flange falling into the die', 'Insufficient shoulder overlap lets the edge drop inside the V opening.'], ['Angle inconsistency', 'Changing support changes penetration response and batch repeatability.'], ['Marks and interference', 'Pressure concentration or punch collision can damage the part.'], ['Rejected parts', 'Wrong location, angle or finished flange dimension drives scrap.'], ['Production repeatability', 'Verified support makes setup values usable across a run.']] },
    sections: [
      ['v-opening', 'Relationship Between V Opening and Minimum Flange', 'A larger V opening normally requires a longer minimum flange because the die shoulders are farther apart. The wider span can reduce tonnage, but it leaves a short edge with less support and usually increases natural inside radius. A narrower V can support a shorter flange more readily, but raises tonnage, die pressure and marking risk. Production selection balances force, radius, flange length and required surface quality.'],
      ['shoulder', 'Die Shoulder Support', 'Before bending, the flange must sit on a die shoulder with useful overlap, not just touch its edge. Shoulder radius influences both support and visible marking. If support is insufficient, the part slips or pivots as the punch enters. A wide die may be perfectly suitable for force capacity yet unable to locate a very short flange.'],
      ['radius', 'Material Thickness and Inside Radius', 'Thicker material normally needs a larger V opening and forms a larger natural radius. The finished flange dimension is also affected by inside radius, bend allowance and bend deduction; a drawn short leg cannot be checked from outside size alone. Very short flanges may need process compensation, a changed blank dimension or purpose-designed tooling.'],
    ],
    materials: { title: 'Material Influence', cards: [['Mild steel', 'A useful baseline for support checks, provided thickness, radius and surface specification are confirmed.'], ['Stainless steel', 'Higher force and stronger springback make short flanges more sensitive to lost support and angle correction.'], ['Aluminum', 'Lower force does not remove risk: softer surfaces deform and mark easily at the die shoulder.'], ['Production decision', 'Strength, temper, finish and allowable marks all affect whether a short flange is feasible.']] },
    chart: { title: 'Practical Minimum Flange Reference Chart', intro: 'Initial air-bending references for early tooling review; verify against the actual punch and die drawing.', headers: ['Material Thickness', 'Typical V Opening Range', 'Approximate Minimum Flange Reference', 'Engineering Notes'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', 'Check cosmetic marking on thin sheet.'], ['1.5 mm', '10-12 mm', '7-9 mm', 'Common sheet setup; confirm bend radius.'], ['2.0 mm', '12-16 mm', '9-12 mm', 'Short legs need clear shoulder seating.'], ['3.0 mm', '20-24 mm', '14-18 mm', 'Review tonnage and formed radius together.'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', 'Trial bend recommended, especially for stainless.']], note: 'These values are engineering references. Actual minimum flange length depends on tooling geometry, material condition and bending method.' },
    problems: { title: 'Common Short Flange Bending Problems', cards: [['Flange slips into V opening', 'The leg is not supported far enough over the shoulder.'], ['Unstable angle', 'The bend line shifts or the workpiece tilts during forming.'], ['Excessive die marks', 'A narrow corrective die concentrates contact pressure.'], ['Cracking near bend line', 'A tight radius or hard material exceeds allowable strain.'], ['Punch interference', 'The short return geometry collides before reaching angle.'], ['Wrong V opening', 'An opening selected only for tonnage cannot support the leg.'], ['Inaccurate final dimension', 'Radius and bend allowance were not included in the flange check.']] },
    solutions: { title: 'Tooling Solutions for Short Flanges', intro: 'Standard tooling does not solve every short flange condition. Validate loading and collision clearance before production.', items: ['Use a narrower V die when capacity, radius and surface limits permit.', 'Use acute tooling or a suitable special punch to establish tight geometry.', 'Specify a custom die where standard shoulder geometry cannot provide support.', 'Evaluate offset forming, staged bending or a modified bend sequence for constrained returns.'] },
    notes: { title: 'Engineering Notes', items: ['Review every short flange against actual tooling before releasing production.', 'Check drawing dimensions against tooling feasibility, inside radius and bend allowance.', 'Use trial bending for tight flanges or uncertain material batches.', 'Provide surface protection for cosmetic components where shoulder contact is visible.', 'Allow a larger safety margin for short flanges in thick stainless steel.'] },
    faqTitle: 'Frequently Asked Questions', faq: [
      ['What is minimum flange length in press brake bending?', 'It is the shortest leg that can be supported reliably on the die shoulders while the bend is formed.'],
      ['Why does V die opening affect minimum flange length?', 'A wider opening places the shoulders farther apart, so a short flange has less supporting overlap.'],
      ['What happens if the flange is too short?', 'It may slip into the opening, shift the bend line, mark badly or fail to reach a repeatable angle.'],
      ['Can I bend a flange shorter than the V opening rule?', 'Sometimes, with verified special tooling or process changes; the result must be proven by clearance, load and trial-bend checks.'],
      ['How do I bend short flanges?', 'Start by checking a narrower compatible V die, then assess acute or special tooling and an alternate sequence.'],
      ['Does material type affect minimum flange length?', 'Yes. Strength, springback, ductility and surface sensitivity affect support margin and acceptable tooling.'],
      ['Why does the flange fall into the die?', 'It falls when the edge no longer overlaps the die shoulder enough to resist punch-induced sliding.'],
    ],
    relatedTitle: 'Related Engineering Tools', relatedAria: 'Related engineering tools',
    relatedLabels: { pressBrakeCalculator: 'Press Brake Calculator', materialDatabase: 'Material Database', vDieSelectionTool: 'V Die Selection Tool', insideRadiusGuide: 'Inside Radius Guide', springbackDatabase: 'Springback Database', bendAllowanceCalculator: 'Bend Allowance Calculator', bendDeductionGuide: 'Bend Deduction Guide', airBendingGuide: 'Air Bending Guide', pressBrakeTonnageGuide: 'Press Brake Tonnage Guide', vDieOpeningGuide: 'How to Choose Press Brake V-Die Opening', minimumFlangeLengthGuide: 'Minimum Flange Length Guide', toolingSelectionGuide: 'Press Brake Tooling Selection Guide', crowningGuide: 'Press Brake Crowning Guide', stainlessSteelBendingGuide: 'Stainless Steel Bending Guide', aluminumBendingGuide: 'Aluminum Bending Guide' },
    diagram: { eyebrow: 'Engineering Visualization', title: 'Minimum Flange Engineering Visualization System', svgTitle: 'Minimum flange support and instability comparison', svgDescription: 'Short flange falling into a V die compared with a correctly supported flange, followed by dimensioned tooling geometry.', instability: 'Short Flange Instability', supportTitle: 'Stable Flange Support', insufficient: 'insufficient support', slips: 'flange slips into die', shortRisk: 'short flange risk', unstable: 'unstable bending', proper: 'proper support', shoulder: 'die shoulder support', correct: 'correct flange length', stable: 'stable bending', geometry: 'TOOLING GEOMETRY AND SUPPORT', vOpening: 'V opening', flangeLength: 'flange length', insideRadius: 'inside radius', punch: 'Punch', sheet: 'Sheet metal', vDie: 'V die' },
  },
  zh: {
    back: '← 返回工程工具中心', eyebrow: '工程指南', title: '最小翻边长度指南',
    subtitle: '专业解析折弯机加工中的最小翻边长度、V 型模支撑、短边稳定性与模具选择。',
    what: { title: '什么是最小翻边长度？', text: '最小翻边长度是折弯过程中能够可靠坐落在下模肩部、并保持定位稳定的最短折弯边。它不只是图纸上的一个尺寸，还受 V 开口、内半径、板厚、折弯方式和模具形状共同控制。短边若失去足够肩部支撑，就会滑入 V 槽、改变弯线位置或造成角度不稳定。' },
    why: { title: '为什么最小翻边长度重要', cards: [['短边失稳', '折弯尚未建立时，过短的边会旋转或滑移。'], ['翻边掉入下模', '肩部搭接不足时，边缘会落入 V 开口。'], ['角度不一致', '支撑变化会改变压入响应与批量重复性。'], ['压痕与干涉', '局部压力或冲头碰撞会损坏零件。'], ['零件报废', '定位、角度或成品翻边尺寸失准会导致拒收。'], ['生产重复性', '验证过的支撑条件才能稳定复用工艺参数。']] },
    sections: [['v-opening', 'V 开口与最小翻边的关系', 'V 开口越大，下模肩部距离越远，通常要求更长的最小翻边。较大开口可以降低吨位，却减少短边的有效支撑并增大自然内半径。较小开口更容易支撑短边，但会提高吨位、接触压力和压痕风险。实际选型必须在吨位、半径、翻边长度和表面质量之间平衡。'], ['shoulder', '下模肩部支撑', '折弯开始前，翻边必须在下模肩部形成有效搭接，而非仅仅碰到肩部边缘。肩部圆角既影响支撑，也影响表面压痕。支撑不足时，工件会在冲头进入时滑移或倾转；宽下模即使承载能力合适，也可能无法定位很短的边。'], ['radius', '板厚与内半径', '厚板通常需要更大的 V 开口，并形成更大的自然内半径。成品翻边尺寸还会受内半径、折弯展开量和折弯扣除影响，因此不能只按外形短边判断可行性。极短翻边可能需要工艺补偿、调整毛坯尺寸或采用专用模具。']],
    materials: { title: '材料影响', cards: [['低碳钢', '可作为支撑核验的常用基准，但仍需确认板厚、半径与表面要求。'], ['不锈钢', '更高折弯力和更强回弹会放大短边失去支撑后的角度控制难度。'], ['铝板', '所需力较低并不代表没有风险；柔软表面更容易在肩部变形或留痕。'], ['工艺判断', '强度、状态、表面等级与允许压痕共同决定短边是否可做。']] },
    chart: { title: '最小翻边实用参考表', intro: '以下为空气折弯早期模具审核参考，最终应结合实际冲头和下模图纸核验。', headers: ['材料厚度', '典型 V 开口范围', '近似最小翻边参考', '工程说明'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', '薄板需注意外观压痕。'], ['1.5 mm', '10-12 mm', '7-9 mm', '常见薄板设定，需确认折弯半径。'], ['2.0 mm', '12-16 mm', '9-12 mm', '短边必须清楚坐落于肩部。'], ['3.0 mm', '20-24 mm', '14-18 mm', '吨位与成形内半径应一并核查。'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', '建议试折，尤其是不锈钢。']], note: '这些数值为工程参考值。实际最小翻边长度会受模具几何形状、材料状态和折弯方式影响。' },
    problems: { title: '短翻边折弯常见问题', cards: [['翻边滑入 V 开口', '短边在肩部上的支撑搭接不足。'], ['角度不稳定', '成形时弯线移动或工件倾转。'], ['压痕过重', '为短边采用窄模时接触压力集中。'], ['弯线附近开裂', '半径过紧或材料偏硬导致应变超限。'], ['冲头干涉', '短回边几何在达到目标角度前碰撞。'], ['V 开口选择错误', '只考虑吨位而未检查短边支撑。'], ['成品尺寸不准', '核验时未计入半径和折弯展开量。']] },
    solutions: { title: '短翻边模具解决方案', intro: '标准模具无法解决所有短翻边工况。投产前必须验证承载与干涉间隙。', items: ['在吨位、半径与表面允许的情况下采用更窄的 V 型模。', '采用锐角模具或合适的特殊冲头建立紧凑几何。', '标准肩部无法支撑时，设计专用下模。', '评估偏置成形、分步折弯或修改折弯顺序。'] },
    notes: { title: '工程说明', items: ['短翻边零件投产前必须对照实际模具审核。', '图纸尺寸应同时核对模具可行性、内半径与折弯展开。', '紧尺寸翻边或材料批次不确定时建议试折。', '外观件应为肩部接触规划表面保护。', '厚不锈钢短翻边应留出更大安全余量。'] },
    faqTitle: '常见问题', faq: [['折弯中的最小翻边长度是什么？', '它是折弯形成过程中能够可靠受到下模肩部支撑的最短折弯边。'], ['为什么 V 型模开口会影响最小翻边？', '开口增大会拉开肩部间距，使短边可获得的支撑搭接减少。'], ['翻边太短会发生什么？', '它可能掉入开口、移动弯线、产生严重压痕或无法稳定获得目标角度。'], ['能否折弯比常用 V 开口规则更短的翻边？', '有时可以，但必须采用经验证的特殊模具或工艺，并核查间隙、载荷和试折结果。'], ['短翻边应怎样折？', '先核查可兼容的较窄 V 型模，再评估锐角/专用模具或改变工序。'], ['材料类型会影响最小翻边吗？', '会。强度、回弹、延展性和表面敏感性都会改变所需支撑余量。'], ['为什么翻边会掉进下模？', '因为边缘与下模肩部的有效搭接不足，无法抵抗冲头作用下的滑移。']],
    relatedTitle: '相关工程工具', relatedAria: '相关工程工具', relatedLabels: { pressBrakeCalculator: '折弯机计算器', materialDatabase: '材料数据库', vDieSelectionTool: 'V 型模具选择工具', insideRadiusGuide: '内半径指南', springbackDatabase: '回弹数据库', bendAllowanceCalculator: '折弯展开计算器', bendDeductionGuide: '折弯扣除量指南', airBendingGuide: '空气折弯指南', pressBrakeTonnageGuide: '折弯机吨位指南', vDieOpeningGuide: '如何选择折弯机 V 型模开口', minimumFlangeLengthGuide: '最小翻边长度指南', toolingSelectionGuide: '折弯机模具选型指南', crowningGuide: '折弯机挠度补偿指南', stainlessSteelBendingGuide: '不锈钢折弯指南', aluminumBendingGuide: '铝板折弯指南' },
    diagram: { eyebrow: '工程可视化', title: '最小翻边工程可视化系统', svgTitle: '最小翻边支撑与失稳对比图', svgDescription: '短翻边掉入 V 型模与正确支撑翻边的对比，以及带尺寸标注的模具结构。', instability: '短翻边失稳', supportTitle: '稳定翻边支撑', insufficient: '支撑不足', slips: '翻边滑入下模', shortRisk: '短边风险', unstable: '折弯不稳定', proper: '正确支撑', shoulder: '下模肩部支撑', correct: '正确翻边长度', stable: '稳定折弯', geometry: '模具几何与支撑', vOpening: 'V 开口', flangeLength: '翻边长度', insideRadius: '内半径', punch: '冲头', sheet: '板材', vDie: 'V 型模' },
  },
  ru: {
    back: '← Назад к инженерным инструментам', eyebrow: 'Инженерное руководство', title: 'Руководство по минимальной длине полки', subtitle: 'Профессиональный справочник по минимальной полке при гибке на листогибе, опоре на V-матрицу, устойчивости коротких полок и выбору оснастки.',
    what: { title: 'Что такое минимальная длина полки?', text: 'Минимальная длина полки - это самая короткая сторона гиба, которая надежно лежит на плечах нижней матрицы во время формования. Это не только размер на чертеже: его определяют раскрытие V, внутренний радиус, толщина, метод гибки и геометрия инструмента. При недостаточной опоре короткая полка соскальзывает в ручей и угол становится нестабильным.' },
    why: { title: 'Почему минимальная полка важна', cards: [['Неустойчивая короткая полка', 'До образования гиба край может повернуться или сдвинуться.'], ['Провал в матрицу', 'Недостаточное перекрытие плеча позволяет краю уйти в V-паз.'], ['Разброс угла', 'Изменение опоры ухудшает повторяемость серии.'], ['Следы и столкновение', 'Высокое давление или контакт с пуансоном повреждают деталь.'], ['Брак', 'Смещение линии гиба и неверный размер ведут к отказу.'], ['Стабильность выпуска', 'Проверенная опора делает настройку повторяемой.']] },
    sections: [['v-opening', 'Связь раскрытия V и минимальной полки', 'При увеличении раскрытия V плечи расходятся, поэтому обычно требуется более длинная полка. Широкая матрица снижает усилие, но ухудшает опору короткой стороны и увеличивает естественный радиус. Узкая матрица помогает короткой полке, но повышает усилие и риск следов.'], ['shoulder', 'Опора на плечи матрицы', 'До начала гибки полка должна иметь рабочее перекрытие плеча. Радиус плеча влияет на опору и отпечатки. При недостаточном перекрытии лист скользит или наклоняется; широкая матрица может не удержать очень короткую полку.'], ['radius', 'Толщина материала и внутренний радиус', 'Толстый лист обычно требует большего раскрытия и формирует больший радиус. Готовый размер полки зависит также от радиуса и припуска на гиб. Для очень коротких полок нужна компенсация процесса или специальная оснастка.']],
    materials: { title: 'Влияние материала', cards: [['Мягкая сталь', 'Практичная исходная база при подтвержденных толщине и радиусе.'], ['Нержавеющая сталь', 'Большее усилие и пружинение повышают чувствительность короткой полки.'], ['Алюминий', 'Мягкая поверхность легче деформируется и получает следы на плечах.'], ['Решение по процессу', 'Прочность, состояние и требования к поверхности определяют применимость.']] },
    chart: { title: 'Практическая таблица минимальной полки', intro: 'Начальные справочные значения для воздушной гибки; проверьте реальную геометрию инструмента.', headers: ['Толщина', 'Типовой диапазон V', 'Ориентир минимальной полки', 'Примечания'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', 'Проверить следы на тонком листе.'], ['1.5 mm', '10-12 mm', '7-9 mm', 'Подтвердить радиус гиба.'], ['2.0 mm', '12-16 mm', '9-12 mm', 'Нужна четкая опора плеча.'], ['3.0 mm', '20-24 mm', '14-18 mm', 'Проверить усилие и радиус.'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', 'Рекомендуется пробная гибка.']], note: 'Значения являются инженерными ориентирами. Фактическая минимальная длина полки зависит от геометрии оснастки, состояния материала и метода гибки.' },
    problems: { title: 'Типичные проблемы короткой полки', cards: [['Полка уходит в V-паз', 'Перекрытия плеча недостаточно.'], ['Нестабильный угол', 'Заготовка смещается во время формования.'], ['Сильные следы', 'Узкая матрица концентрирует давление.'], ['Трещины у гиба', 'Радиус или состояние материала слишком жесткие.'], ['Контакт с пуансоном', 'Геометрия возврата сталкивается с инструментом.'], ['Неверное раскрытие V', 'Выбор сделан без проверки опоры.'], ['Неточный размер', 'Не учтены радиус и припуск на гиб.']] },
    solutions: { title: 'Оснастка для коротких полок', intro: 'Стандартная оснастка решает не все случаи коротких полок. Перед выпуском проверьте нагрузку и зазоры.', items: ['Применить более узкую V-матрицу, если допускают усилие, радиус и поверхность.', 'Использовать остроугольную оснастку или специальный пуансон.', 'Назначить специальную матрицу, если обычное плечо не дает опоры.', 'Оценить смещенную формовку, гибку этапами или иной порядок операций.'] },
    notes: { title: 'Инженерные замечания', items: ['Короткую полку следует проверять по фактической оснастке до производства.', 'Размеры чертежа нужно сопоставлять с радиусом и припуском на гиб.', 'Для предельных полок рекомендуется пробная гибка.', 'Для декоративных деталей нужна защита поверхности.', 'Для толстой нержавеющей стали необходим больший запас.'] },
    faqTitle: 'Частые вопросы', faq: [['Что такое минимальная длина полки?', 'Это самая короткая сторона, надежно поддерживаемая плечами матрицы при гибке.'], ['Почему раскрытие V влияет на полку?', 'При большем раскрытии плечи дальше друг от друга и опора короткой стороны уменьшается.'], ['Что будет, если полка слишком короткая?', 'Она может провалиться, сместить гиб или дать нестабильный угол.'], ['Можно ли гнуть короче обычного правила?', 'Иногда, при проверенной специальной оснастке и пробной гибке.'], ['Как гнуть короткие полки?', 'Проверьте более узкую совместимую матрицу, затем специальный инструмент и последовательность.'], ['Влияет ли материал?', 'Да, прочность, пружинение, пластичность и поверхность меняют необходимый запас.'], ['Почему полка падает в матрицу?', 'Ее перекрытие плеча недостаточно для сопротивления скольжению под пуансоном.']],
    relatedTitle: 'Связанные инженерные инструменты', relatedAria: 'Связанные инженерные инструменты', relatedLabels: { pressBrakeCalculator: 'Калькулятор листогиба', materialDatabase: 'База материалов', vDieSelectionTool: 'Подбор V-матрицы', insideRadiusGuide: 'Справочник внутреннего радиуса', springbackDatabase: 'База пружинения', bendAllowanceCalculator: 'Калькулятор припуска на гиб', bendDeductionGuide: 'Руководство по вычету гиба', airBendingGuide: 'Руководство по воздушной гибке', pressBrakeTonnageGuide: 'Руководство по тоннажу пресса', vDieOpeningGuide: 'Выбор раскрытия V-матрицы', minimumFlangeLengthGuide: 'Руководство по минимальной длине полки', toolingSelectionGuide: 'Выбор оснастки листогиба', crowningGuide: 'Руководство по компенсации прогиба', stainlessSteelBendingGuide: 'Руководство по гибке нержавеющей стали', aluminumBendingGuide: 'Руководство по гибке алюминия' },
    diagram: { eyebrow: 'Инженерная схема', title: 'Система визуализации минимальной полки', svgTitle: 'Сравнение опоры и неустойчивости минимальной полки', svgDescription: 'Сравнение короткой полки, падающей в V-матрицу, и устойчиво поддерживаемой полки с размерами инструмента.', instability: 'Неустойчивая короткая полка', supportTitle: 'Устойчивая опора полки', insufficient: 'недостаточная опора', slips: 'полка уходит в матрицу', shortRisk: 'риск короткой полки', unstable: 'нестабильная гибка', proper: 'правильная опора', shoulder: 'опора плеча матрицы', correct: 'правильная длина полки', stable: 'стабильная гибка', geometry: 'ГЕОМЕТРИЯ И ОПОРА', vOpening: 'раскрытие V', flangeLength: 'длина полки', insideRadius: 'внутренний радиус', punch: 'Пуансон', sheet: 'Лист', vDie: 'V-матрица' },
  },
  es: {
    back: '← Volver a herramientas de ingeniería', eyebrow: 'Guía de ingeniería', title: 'Guía de longitud mínima de pestaña', subtitle: 'Guía profesional para comprender la longitud mínima de pestaña en plegadora, el apoyo de la matriz V, la estabilidad de pestañas cortas y la selección de utillaje.',
    what: { title: '¿Qué es la longitud mínima de pestaña?', text: 'Es la pata de plegado más corta que puede mantenerse apoyada de forma fiable sobre los hombros de la matriz inferior durante el conformado. No es solo una cota del plano: la abertura V, el radio interior, el espesor, el método y la geometría del utillaje controlan su viabilidad. Sin apoyo suficiente, la pestaña corta cae dentro de la V o forma un ángulo inestable.' },
    why: { title: 'Por qué importa la longitud mínima', cards: [['Inestabilidad de pestaña', 'Una pata corta puede girar o deslizar antes de formar el pliegue.'], ['Caída en la matriz', 'La falta de solape sobre el hombro deja entrar el borde en la V.'], ['Ángulo inconsistente', 'El apoyo variable reduce la repetibilidad.'], ['Marcas e interferencia', 'La presión localizada o la colisión dañan la pieza.'], ['Rechazo de piezas', 'Posición o dimensión final incorrectas generan scrap.'], ['Producción repetible', 'El apoyo verificado estabiliza el proceso.']] },
    sections: [['v-opening', 'Relación entre abertura V y pestaña mínima', 'Al aumentar la abertura V, normalmente aumenta la pestaña mínima porque los hombros están más separados. Una V grande reduce tonelaje, pero exige más apoyo y aumenta el radio natural. Una V pequeña ayuda a la pestaña corta, aunque eleva tonelaje y riesgo de marcas.'], ['shoulder', 'Apoyo en el hombro de la matriz', 'La pestaña debe asentarse con solape útil sobre el hombro antes de plegar. El radio del hombro afecta tanto al apoyo como a la huella superficial. Sin apoyo, la chapa resbala o bascula; una matriz ancha puede no localizar una pestaña muy corta.'], ['radius', 'Espesor y radio interior', 'Los espesores mayores suelen requerir una V mayor y producen radios mayores. La dimensión final depende del radio y del desarrollo de plegado. Las pestañas muy cortas pueden exigir compensación o utillaje especial.']],
    materials: { title: 'Influencia del material', cards: [['Acero dulce', 'Referencia de partida útil si se verifican espesor y radio.'], ['Acero inoxidable', 'Más fuerza y retorno elástico hacen más crítica la pérdida de apoyo.'], ['Aluminio', 'Su superficie blanda puede deformarse o marcarse con facilidad.'], ['Decisión de proceso', 'Resistencia, estado y acabado determinan la viabilidad real.']] },
    chart: { title: 'Tabla práctica de pestaña mínima', intro: 'Referencias iniciales para plegado al aire; confirmar con la geometría real del utillaje.', headers: ['Espesor', 'Rango V típico', 'Referencia aproximada de pestaña mínima', 'Notas técnicas'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', 'Comprobar marcas cosméticas.'], ['1.5 mm', '10-12 mm', '7-9 mm', 'Confirmar radio formado.'], ['2.0 mm', '12-16 mm', '9-12 mm', 'Requiere apoyo claro del hombro.'], ['3.0 mm', '20-24 mm', '14-18 mm', 'Revisar tonelaje y radio.'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', 'Se recomienda plegado de prueba.']], note: 'Estos valores son referencias de ingeniería. La longitud mínima real depende de la geometría del utillaje, el estado del material y el método de plegado.' },
    problems: { title: 'Problemas habituales con pestañas cortas', cards: [['La pestaña cae en la V', 'No existe solape suficiente sobre el hombro.'], ['Ángulo inestable', 'La pieza se desplaza durante el plegado.'], ['Marcas excesivas', 'Una matriz estrecha concentra presión.'], ['Grietas en el pliegue', 'Radio o material demasiado severos.'], ['Interferencia con punzón', 'La geometría choca antes del ángulo final.'], ['Abertura V incorrecta', 'Se eligió sin comprobar apoyo.'], ['Dimensión inexacta', 'No se incluyeron radio y desarrollo.']] },
    solutions: { title: 'Soluciones de utillaje para pestañas cortas', intro: 'El utillaje estándar no resuelve todas las pestañas cortas. Verifique carga y holgura antes de fabricar.', items: ['Elegir una matriz V más estrecha si tonelaje, radio y acabado lo permiten.', 'Utilizar utillaje agudo o un punzón especial adecuado.', 'Diseñar una matriz especial cuando el hombro normal no soporte la pieza.', 'Evaluar conformado offset, plegado escalonado o una secuencia modificada.'] },
    notes: { title: 'Notas de ingeniería', items: ['Revisar toda pestaña corta con el utillaje real antes de producir.', 'Contrastar cotas del plano con radio y desarrollo factibles.', 'Realizar prueba de plegado para pestañas límite.', 'Proteger la superficie en piezas cosméticas.', 'Dejar mayor margen en inoxidable grueso.'] },
    faqTitle: 'Preguntas frecuentes', faq: [['¿Qué es la longitud mínima de pestaña?', 'La pata más corta que puede apoyarse con fiabilidad durante el plegado.'], ['¿Por qué influye la abertura V?', 'Una V más ancha separa los hombros y reduce el apoyo de una pata corta.'], ['¿Qué ocurre si la pestaña es demasiado corta?', 'Puede caer, desplazar el pliegue o producir un ángulo no repetible.'], ['¿Se puede plegar más corto que la regla habitual?', 'A veces, con utillaje especial validado y pruebas.'], ['¿Cómo se pliegan pestañas cortas?', 'Revise primero una V estrecha compatible y después utillaje o secuencia especial.'], ['¿Influye el material?', 'Sí; resistencia, retorno, ductilidad y superficie cambian el margen necesario.'], ['¿Por qué cae la pestaña en la matriz?', 'Porque el borde no solapa suficientemente el hombro para resistir el deslizamiento.']],
    relatedTitle: 'Herramientas de ingeniería relacionadas', relatedAria: 'Herramientas de ingeniería relacionadas', relatedLabels: { pressBrakeCalculator: 'Calculadora de plegadora', materialDatabase: 'Base de datos de materiales', vDieSelectionTool: 'Selección de matriz V', insideRadiusGuide: 'Guía de radio interior', springbackDatabase: 'Base de datos de retorno elástico', bendAllowanceCalculator: 'Calculadora de desarrollo de plegado', bendDeductionGuide: 'Guía de deducción de plegado', airBendingGuide: 'Guía de plegado al aire', pressBrakeTonnageGuide: 'Guía de tonelaje para plegadoras', vDieOpeningGuide: 'Selección de abertura de matriz V', minimumFlangeLengthGuide: 'Guía de longitud mínima de pestaña', toolingSelectionGuide: 'Guía de selección de utillaje', crowningGuide: 'Guía de compensación de flecha', stainlessSteelBendingGuide: 'Guía de plegado de acero inoxidable', aluminumBendingGuide: 'Guía de plegado de aluminio' },
    diagram: { eyebrow: 'Visualización técnica', title: 'Sistema técnico de pestaña mínima', svgTitle: 'Comparación del apoyo de pestaña mínima', svgDescription: 'Una pestaña corta que cae en una matriz V comparada con una pestaña correctamente apoyada.', instability: 'Inestabilidad de pestaña corta', supportTitle: 'Apoyo estable de pestaña', insufficient: 'apoyo insuficiente', slips: 'la pestaña cae en la matriz', shortRisk: 'riesgo de pestaña corta', unstable: 'plegado inestable', proper: 'apoyo correcto', shoulder: 'apoyo del hombro', correct: 'longitud correcta', stable: 'plegado estable', geometry: 'GEOMETRÍA Y APOYO', vOpening: 'abertura V', flangeLength: 'longitud de pestaña', insideRadius: 'radio interior', punch: 'Punzón', sheet: 'Chapa', vDie: 'Matriz V' },
  },
  tr: {
    back: '← Mühendislik araçlarına dön', eyebrow: 'Mühendislik kılavuzu', title: 'Minimum Flanş Boyu Kılavuzu', subtitle: 'Abkant bükmede minimum flanş boyunu, V kalıp desteğini, kısa flanş kararlılığını ve takım seçimini anlamak için profesyonel kılavuz.',
    what: { title: 'Minimum flanş boyu nedir?', text: 'Minimum flanş boyu, büküm sırasında alt kalıp omuzlarında güvenilir biçimde desteklenebilen en kısa büküm ayağıdır. Yalnızca çizim ölçüsü değildir; V açıklığı, iç radyüs, sac kalınlığı, yöntem ve takım geometrisi belirleyicidir. Destek yetersizse kısa flanş V içine kayar ve açı kararsız olur.' },
    why: { title: 'Minimum flanş boyu neden önemlidir', cards: [['Kısa flanş kararsızlığı', 'Büküm oluşmadan kenar dönebilir veya kayabilir.'], ['Kalıba düşme', 'Yetersiz omuz bindirmesi kenarı V açıklığına sokar.'], ['Açı değişkenliği', 'Değişen destek tekrarlanabilirliği azaltır.'], ['İz ve çarpışma', 'Yüksek temas veya zımba teması parçayı bozar.'], ['Hurda parça', 'Yanlış konum ve ölçü reddedilir.'], ['Üretim kararlılığı', 'Doğrulanmış destek ayarı tekrar kullanılabilir kılar.']] },
    sections: [['v-opening', 'V açıklığı ile minimum flanş ilişkisi', 'V açıklığı büyüdükçe omuzlar uzaklaşır ve genellikle daha uzun minimum flanş gerekir. Geniş V tonajı azaltabilir; ancak kısa kenar desteğini azaltır ve doğal iç radyüsü büyütür. Dar V kısa flanşı destekler, fakat tonajı ve iz riskini artırır.'], ['shoulder', 'Kalıp omzu desteği', 'Bükmeden önce flanş, omuz üzerinde anlamlı bir bindirme ile oturmalıdır. Omuz radyüsü hem desteği hem izi etkiler. Destek eksikse parça kayar veya yatar; geniş bir kalıp çok kısa bir flanşı konumlandıramayabilir.'], ['radius', 'Malzeme kalınlığı ve iç radyüs', 'Kalın sac genellikle daha geniş V ve daha büyük doğal radyüs ister. Nihai flanş ölçüsü iç radyüs ve büküm payından etkilenir. Çok kısa flanşlar proses telafisi veya özel takım gerektirebilir.']],
    materials: { title: 'Malzeme etkisi', cards: [['Yumuşak çelik', 'Kalınlık ve radyüs doğrulandığında iyi bir başlangıç referansıdır.'], ['Paslanmaz çelik', 'Daha yüksek kuvvet ve geri esneme kısa kenarı daha hassas hale getirir.'], ['Alüminyum', 'Yumuşak yüzey omuz temasında kolay deforme olur veya iz alır.'], ['Proses kararı', 'Dayanım, temper ve yüzey beklentisi uygulanabilirliği belirler.']] },
    chart: { title: 'Pratik minimum flanş referans tablosu', intro: 'Havada bükme için başlangıç referanslarıdır; gerçek takım geometrisi ile doğrulayın.', headers: ['Kalınlık', 'Tipik V aralığı', 'Yaklaşık minimum flanş', 'Mühendislik notu'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', 'İnce sacda görünür izleri kontrol edin.'], ['1.5 mm', '10-12 mm', '7-9 mm', 'Oluşan radyüsü doğrulayın.'], ['2.0 mm', '12-16 mm', '9-12 mm', 'Omuzda açık destek gerekir.'], ['3.0 mm', '20-24 mm', '14-18 mm', 'Tonaj ve radyüsü birlikte inceleyin.'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', 'Deneme bükümü önerilir.']], note: 'Bu değerler mühendislik referansıdır. Gerçek minimum flanş boyu takım geometrisine, malzeme durumuna ve bükme yöntemine bağlıdır.' },
    problems: { title: 'Yaygın kısa flanş sorunları', cards: [['Flanş V içine kayar', 'Omuz bindirmesi yeterli değildir.'], ['Kararsız açı', 'Parça büküm sırasında yer değiştirir.'], ['Aşırı kalıp izi', 'Dar kalıp basıncı yoğunlaştırır.'], ['Büküm hattında çatlak', 'Radyüs veya malzeme koşulu fazla serttir.'], ['Zımba çarpışması', 'Geometri hedef açıdan önce temas eder.'], ['Yanlış V seçimi', 'Destek kontrol edilmemiştir.'], ['Hatalı nihai ölçü', 'Radyüs ve büküm payı hesaba katılmamıştır.']] },
    solutions: { title: 'Kısa flanşlar için takım çözümleri', intro: 'Standart takım her kısa flanş koşulunu çözmez. Üretimden önce yük ve boşluğu doğrulayın.', items: ['Tonaj, radyüs ve yüzey uygunsa daha dar V kalıp kullanın.', 'Akut takım veya uygun özel zımba değerlendirin.', 'Standart omuz destek veremiyorsa özel kalıp tasarlayın.', 'Ofset şekillendirme, kademeli büküm veya farklı sıra değerlendirin.'] },
    notes: { title: 'Mühendislik notları', items: ['Kısa flanşları üretimden önce gerçek takım ile kontrol edin.', 'Çizim ölçülerini radyüs ve büküm payı ile birlikte inceleyin.', 'Sınır flanşlarda deneme bükümü yapın.', 'Kozmetik parçalarda yüzeyi koruyun.', 'Kalın paslanmaz kısa flanşlarda daha büyük emniyet payı kullanın.'] },
    faqTitle: 'Sık sorulan sorular', faq: [['Minimum flanş boyu nedir?', 'Kalıp omuzlarında güvenli biçimde desteklenebilen en kısa büküm ayağıdır.'], ['V açıklığı neden etkiler?', 'Geniş açıklık omuzları ayırır ve kısa ayağın desteğini azaltır.'], ['Flanş çok kısa olursa ne olur?', 'Kalıba kayabilir, büküm hattı değişebilir veya açı tekrarlanamaz.'], ['Kuraldan daha kısa flanş bükülebilir mi?', 'Bazen, doğrulanmış özel takım ve deneme bükümü ile.'], ['Kısa flanş nasıl bükülür?', 'Önce uyumlu dar V kalıbı, ardından özel takım veya işlem sırasını değerlendirin.'], ['Malzeme etkiler mi?', 'Evet; dayanım, geri esneme, süneklik ve yüzey gereken payı değiştirir.'], ['Flanş neden kalıba düşer?', 'Kenar, kaymayı önleyecek kadar omuz üzerinde kalmaz.']],
    relatedTitle: 'İlgili mühendislik araçları', relatedAria: 'İlgili mühendislik araçları', relatedLabels: { pressBrakeCalculator: 'Abkant pres hesaplayıcısı', materialDatabase: 'Malzeme veritabanı', vDieSelectionTool: 'V kalıp seçim aracı', insideRadiusGuide: 'İç radyüs kılavuzu', springbackDatabase: 'Geri esneme veritabanı', bendAllowanceCalculator: 'Büküm payı hesaplayıcısı', bendDeductionGuide: 'Büküm Düşümü Kılavuzu', airBendingGuide: 'Havada bükme kılavuzu', pressBrakeTonnageGuide: 'Abkant pres tonaj kılavuzu', vDieOpeningGuide: 'V kalıp açıklığı seçimi', minimumFlangeLengthGuide: 'Minimum Flanş Boyu Kılavuzu', toolingSelectionGuide: 'Abkant pres takım seçimi kılavuzu', crowningGuide: 'Abkant pres sehim kompanzasyonu kılavuzu', stainlessSteelBendingGuide: 'Paslanmaz Çelik Büküm Kılavuzu', aluminumBendingGuide: 'Alüminyum Büküm Kılavuzu' },
    diagram: { eyebrow: 'Mühendislik görselleştirmesi', title: 'Minimum flanş mühendislik sistemi', svgTitle: 'Minimum flanş destek karşılaştırması', svgDescription: 'V kalıba kayan kısa flanş ile doğru destekli flanşın takım ölçüleriyle karşılaştırması.', instability: 'Kısa flanş kararsızlığı', supportTitle: 'Kararlı flanş desteği', insufficient: 'yetersiz destek', slips: 'flanş kalıba kayar', shortRisk: 'kısa flanş riski', unstable: 'kararsız büküm', proper: 'doğru destek', shoulder: 'kalıp omzu desteği', correct: 'doğru flanş boyu', stable: 'kararlı büküm', geometry: 'TAKIM GEOMETRİSİ VE DESTEK', vOpening: 'V açıklığı', flangeLength: 'flanş boyu', insideRadius: 'iç radyüs', punch: 'Zımba', sheet: 'Sac', vDie: 'V kalıp' },
  },
  id: {
    back: '← Kembali ke pusat alat teknik', eyebrow: 'Panduan Teknik', title: 'Panduan Panjang Flange Minimum', subtitle: 'Panduan profesional untuk memahami panjang flange minimum pada bending press brake, tumpuan V-die, kestabilan flange pendek, dan pemilihan tooling.',
    what: { title: 'Apa itu panjang flange minimum?', text: 'Panjang flange minimum adalah kaki tekukan terpendek yang tetap tertumpu secara andal di bahu die bawah saat bending berlangsung. Ini bukan sekadar ukuran gambar; bukaan V, radius dalam, ketebalan, metode bending, dan geometri tooling menentukan kelayakannya. Tanpa tumpuan cukup, flange pendek meluncur ke dalam V dan sudut menjadi tidak stabil.' },
    why: { title: 'Mengapa panjang flange minimum penting', cards: [['Flange pendek tidak stabil', 'Kaki dapat berputar atau bergeser sebelum tekukan terbentuk.'], ['Jatuh ke dalam die', 'Tumpang tindih bahu yang kurang membuat tepi masuk ke V.'], ['Sudut tidak konsisten', 'Perubahan tumpuan merusak repeatability.'], ['Bekas dan interferensi', 'Tekanan lokal atau benturan punch merusak part.'], ['Part ditolak', 'Lokasi dan dimensi akhir salah menjadi scrap.'], ['Produksi berulang', 'Tumpuan tervalidasi menstabilkan setup.']] },
    sections: [['v-opening', 'Hubungan bukaan V dan flange minimum', 'Bukaan V yang lebih besar biasanya memerlukan flange minimum lebih panjang karena jarak bahu die bertambah. V besar menurunkan tonase, tetapi mengurangi dukungan flange pendek dan memperbesar radius alami. V kecil lebih mudah mendukung flange pendek, namun meningkatkan tonase dan risiko bekas.'], ['shoulder', 'Tumpuan bahu die', 'Sebelum bending, flange harus duduk dengan tumpang tindih efektif di atas bahu die. Radius bahu memengaruhi tumpuan dan marking. Bila tumpuan kurang, plat meluncur atau miring; die lebar dapat gagal menahan flange yang sangat pendek.'], ['radius', 'Ketebalan material dan radius dalam', 'Plat lebih tebal umumnya memerlukan V lebih besar dan menghasilkan radius alami lebih besar. Dimensi flange akhir turut dipengaruhi radius serta bend allowance. Flange sangat pendek dapat memerlukan kompensasi proses atau tooling khusus.']],
    materials: { title: 'Pengaruh material', cards: [['Mild steel', 'Acuan awal yang berguna bila ketebalan dan radius dikonfirmasi.'], ['Stainless steel', 'Gaya dan springback lebih besar membuat flange pendek lebih sensitif.'], ['Aluminium', 'Permukaan lunak lebih mudah berubah bentuk atau berbekas di bahu.'], ['Keputusan proses', 'Kekuatan, temper, dan kebutuhan permukaan menentukan kelayakan.']] },
    chart: { title: 'Tabel referensi praktis flange minimum', intro: 'Referensi awal untuk air bending; verifikasi dengan geometri tooling aktual.', headers: ['Ketebalan', 'Rentang V umum', 'Acuan flange minimum', 'Catatan teknik'], rows: [['1.0 mm', '6-8 mm', '5-7 mm', 'Periksa bekas pada permukaan tipis.'], ['1.5 mm', '10-12 mm', '7-9 mm', 'Konfirmasi radius hasil tekuk.'], ['2.0 mm', '12-16 mm', '9-12 mm', 'Butuh dudukan bahu yang jelas.'], ['3.0 mm', '20-24 mm', '14-18 mm', 'Tinjau tonase dan radius.'], ['4.0-6.0 mm', '32-48 mm', '22-34 mm', 'Trial bending disarankan.']], note: 'Nilai ini merupakan referensi teknik. Panjang flange minimum aktual bergantung pada geometri tooling, kondisi material, dan metode bending.' },
    problems: { title: 'Masalah umum bending flange pendek', cards: [['Flange meluncur ke V', 'Tumpuan di bahu tidak cukup.'], ['Sudut tidak stabil', 'Benda kerja bergeser saat forming.'], ['Bekas die berlebih', 'Die sempit memusatkan tekanan.'], ['Retak dekat garis tekuk', 'Radius atau kondisi material terlalu berat.'], ['Interferensi punch', 'Geometri berbenturan sebelum sudut tercapai.'], ['Bukaan V salah', 'Pemilihan tidak mengecek tumpuan.'], ['Dimensi akhir salah', 'Radius dan bend allowance terlewat.']] },
    solutions: { title: 'Solusi tooling untuk flange pendek', intro: 'Tooling standar tidak menyelesaikan semua kondisi flange pendek. Validasi beban dan clearance sebelum produksi.', items: ['Pilih V-die lebih sempit bila tonase, radius, dan permukaan memungkinkan.', 'Gunakan acute tooling atau punch khusus yang sesuai.', 'Rancang die khusus bila bahu standar tidak memberi tumpuan.', 'Evaluasi offset forming, bending bertahap, atau urutan yang diubah.'] },
    notes: { title: 'Catatan teknik', items: ['Tinjau flange pendek dengan tooling nyata sebelum produksi.', 'Cocokkan ukuran gambar dengan radius dan bend allowance yang memungkinkan.', 'Lakukan trial bending untuk flange yang ketat.', 'Lindungi permukaan komponen kosmetik.', 'Berikan margin lebih besar untuk stainless tebal dengan flange pendek.'] },
    faqTitle: 'Pertanyaan yang sering diajukan', faq: [['Apa itu panjang flange minimum?', 'Kaki tekukan terpendek yang dapat ditumpu dengan andal pada bahu die selama bending.'], ['Mengapa bukaan V memengaruhi flange minimum?', 'Bukaan lebih lebar menjauhkan bahu sehingga tumpuan kaki pendek berkurang.'], ['Apa yang terjadi jika flange terlalu pendek?', 'Flange dapat jatuh, menggeser garis tekuk, atau menghasilkan sudut yang tidak berulang.'], ['Bisakah bending lebih pendek dari aturan umum?', 'Kadang bisa dengan tooling khusus tervalidasi dan trial bending.'], ['Bagaimana menekuk flange pendek?', 'Periksa V sempit yang kompatibel, lalu tooling khusus atau urutan alternatif.'], ['Apakah material berpengaruh?', 'Ya; kekuatan, springback, daktilitas, dan permukaan mengubah margin yang dibutuhkan.'], ['Mengapa flange jatuh ke die?', 'Tepi tidak cukup bertumpu di bahu untuk menahan geseran akibat punch.']],
    relatedTitle: 'Alat teknik terkait', relatedAria: 'Alat teknik terkait', relatedLabels: { pressBrakeCalculator: 'Kalkulator press brake', materialDatabase: 'Database material', vDieSelectionTool: 'Alat pemilihan V-die', insideRadiusGuide: 'Panduan radius dalam', springbackDatabase: 'Database springback', bendAllowanceCalculator: 'Kalkulator bend allowance', bendDeductionGuide: 'Panduan Bend Deduction', airBendingGuide: 'Panduan tekuk udara', pressBrakeTonnageGuide: 'Panduan tonase press brake', vDieOpeningGuide: 'Pemilihan bukaan cetakan V', minimumFlangeLengthGuide: 'Panduan Panjang Flange Minimum', toolingSelectionGuide: 'Panduan pemilihan perkakas', crowningGuide: 'Panduan kompensasi lendutan', stainlessSteelBendingGuide: 'Panduan Tekuk Stainless Steel', aluminumBendingGuide: 'Panduan Tekuk Aluminium' },
    diagram: { eyebrow: 'Visualisasi teknik', title: 'Sistem visualisasi flange minimum', svgTitle: 'Perbandingan tumpuan flange minimum', svgDescription: 'Flange pendek yang jatuh ke V-die dibanding flange tertumpu benar beserta dimensi tooling.', instability: 'Flange pendek tidak stabil', supportTitle: 'Tumpuan flange stabil', insufficient: 'tumpuan kurang', slips: 'flange masuk ke die', shortRisk: 'risiko flange pendek', unstable: 'bending tidak stabil', proper: 'tumpuan benar', shoulder: 'tumpuan bahu die', correct: 'panjang flange benar', stable: 'bending stabil', geometry: 'GEOMETRI DAN TUMPUAN', vOpening: 'bukaan V', flangeLength: 'panjang flange', insideRadius: 'radius dalam', punch: 'Punch', sheet: 'Plat', vDie: 'V-die' },
  },
}

function createStructuredData() {
  const page = content.en
  return { '@context': 'https://schema.org', '@graph': [
    { '@type': 'WebPage', name: page.title, description: page.seoDescription, url: getSiteUrl(routePath), isPartOf: { '@type': 'WebSite', name: 'ZYCO Engineering Hub', url: getSiteUrl('/engineering-tools') } },
    { '@type': 'TechArticle', headline: page.title, description: page.seoDescription, author: { '@type': 'Organization', name: 'ZYCO' }, publisher: { '@type': 'Organization', name: 'ZYCO', url: getSiteUrl('/') }, mainEntityOfPage: getSiteUrl(routePath) },
    { '@type': 'FAQPage', mainEntity: page.faq.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
  ] }
}

function Card({ title, text }) { return <article className='zyco-flange__card'><h3>{title}</h3><p>{text}</p></article> }

export default function MinimumFlangeLengthGuide({ language = 'en', setLanguage = () => {} }) {
  const page = content[language] || content.en
  const sharedText = getEngineeringText(language)
  useEffect(() => {
    setPageSEO({ title: `${content.en.title} | ZYCO Engineering Hub`, description: content.en.seoDescription, keywords: content.en.keywords, canonicalPath: routePath })
    setStructuredData({ id: 'minimum-flange-length-guide-jsonld', data: createStructuredData() })
  }, [])

  return (
    <>
      <style>{`
        .zyco-flange { min-height:100vh; box-sizing:border-box; padding:52px 22px; background:radial-gradient(circle at 16% 12%,rgba(96,165,250,.34),transparent 30%),radial-gradient(circle at 84% 20%,rgba(14,165,233,.22),transparent 28%),linear-gradient(145deg,#071224 0%,#0b1f3f 42%,#12366e 74%,#1d4ed8 100%); color:#fff; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; position:relative; overflow:hidden; }
        .zyco-flange::before { content:""; position:absolute; inset:0; background-image:linear-gradient(rgba(96,165,250,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(96,165,250,.08) 1px,transparent 1px); background-size:42px 42px; mask-image:linear-gradient(to bottom,rgba(0,0,0,.9),transparent 78%); pointer-events:none; }
        .zyco-flange__shell { width:min(1180px,100%); margin:0 auto; position:relative; z-index:1; }
        .zyco-flange__hero { padding:38px 36px; margin-bottom:22px; border:1px solid rgba(191,219,254,.2); border-radius:30px; background:linear-gradient(145deg,rgba(255,255,255,.14),rgba(255,255,255,.06)); backdrop-filter:blur(16px); box-shadow:0 28px 68px rgba(2,8,23,.2); }
        .zyco-flange__back,.zyco-flange__tool { display:inline-flex; align-items:center; justify-content:center; box-sizing:border-box; text-decoration:none; color:#fff; font-size:15px; font-weight:800; transition:all .25s ease; }
        .zyco-flange__back { width:fit-content; max-width:min(100%,480px); min-height:44px; margin:0 0 22px; padding:0 16px; border:1px solid rgba(147,197,253,.46); border-radius:999px; background:linear-gradient(145deg,rgba(15,23,42,.34),rgba(37,99,235,.12)); color:#bfdbfe; }
        .zyco-flange__back:hover { transform:translateY(-2px); border-color:rgba(125,211,252,.7); color:#fff; background:rgba(37,99,235,.42); box-shadow:0 14px 32px rgba(37,99,235,.32),0 0 0 1px rgba(125,211,252,.16); }
        .zyco-flange__eyebrow { margin:0; color:#7dd3fc; font-size:12px; font-weight:800; letter-spacing:.2em; text-transform:uppercase; }
        .zyco-flange__title { max-width:920px; margin:14px 0 18px; font-size:clamp(34px,5vw,54px); line-height:1.08; letter-spacing:-.05em; }
        .zyco-flange__subtitle { max-width:930px; margin:0; color:#dbeafe; font-size:18px; line-height:1.72; }
        .zyco-flange__panel { padding:28px; margin-top:18px; border:1px solid rgba(191,219,254,.16); border-radius:25px; background:rgba(10,30,61,.48); backdrop-filter:blur(12px); }
        .zyco-flange__section-title { margin:0 0 14px; color:#fff; font-size:25px; letter-spacing:-.035em; }
        .zyco-flange__copy { margin:0; color:#cbd5e1; font-size:16px; line-height:1.75; }
        .zyco-flange__grid,.zyco-flange__cards { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px; }
        .zyco-flange__cards { gap:12px; margin-top:16px; }
        .zyco-flange__card { padding:18px; border:1px solid rgba(191,219,254,.13); border-radius:18px; background:rgba(30,64,112,.34); }
        .zyco-flange__card h3 { margin:0 0 8px; color:#eff6ff; font-size:16px; line-height:1.45; }
        .zyco-flange__card p { margin:0; color:#bfdbfe; font-size:14px; line-height:1.65; }
        .zyco-flange__table-wrap { overflow-x:auto; border:1px solid rgba(191,219,254,.16); border-radius:18px; margin-top:18px; }
        .zyco-flange__table { width:100%; min-width:760px; border-collapse:collapse; }
        .zyco-flange__table th,.zyco-flange__table td { padding:14px 16px; border-bottom:1px solid rgba(191,219,254,.1); text-align:left; }
        .zyco-flange__table th { color:#bae6fd; background:rgba(30,64,112,.38); font-size:13px; }
        .zyco-flange__table td { color:#e2e8f0; font-size:14px; line-height:1.55; }
        .zyco-flange__reference { margin:16px 0 0; color:#93c5fd; font-size:14px; line-height:1.65; font-weight:650; }
        .zyco-flange__list,.zyco-flange__faq { display:grid; gap:12px; padding:0; margin:0; list-style:none; }
        .zyco-flange__list li,.zyco-flange__faq article { padding:17px 20px; border:1px solid rgba(191,219,254,.12); border-radius:18px; background:rgba(30,64,112,.3); }
        .zyco-flange__faq h3 { margin:0 0 8px; color:#eff6ff; font-size:16px; }
        .zyco-flange__tools { display:flex; flex-wrap:wrap; gap:12px; }
        .zyco-flange__tool { min-height:46px; padding:0 18px; border:1px solid rgba(96,165,250,.18); border-radius:16px; background:linear-gradient(135deg,#1e3a8a 0%,#2563eb 48%,#60a5fa 100%); box-shadow:0 12px 30px rgba(37,99,235,.34); }
        .zyco-flange__tool:hover { transform:translateY(-4px); border-color:rgba(125,211,252,.7); color:#fff; background:rgba(37,99,235,.4); box-shadow:0 14px 30px rgba(56,189,248,.22),0 7px 22px rgba(2,8,23,.22); }
        @media (max-width:840px) { .zyco-flange__grid,.zyco-flange__cards { grid-template-columns:1fr; } }
        @media (max-width:760px) { .zyco-flange { padding:22px 14px; } .zyco-flange__hero,.zyco-flange__panel { padding:22px; border-radius:22px; } .zyco-flange__subtitle { font-size:16px; } }
        @media (max-width:640px) { .zyco-flange__back,.zyco-flange__tool { width:100%; } }
      `}</style>
      <main className='zyco-flange'>
        <div className='zyco-flange__shell'>
          <header className='zyco-flange__hero'>
            <a className='zyco-flange__back' href='/engineering' aria-label={page.back}>{page.back}</a>
            <LanguageSwitcher className='zyco-page-language-switcher' language={language} setLanguage={setLanguage} />
            <p className='zyco-flange__eyebrow'>{page.eyebrow}</p><h1 className='zyco-flange__title'>{page.title}</h1><p className='zyco-flange__subtitle'>{page.subtitle}</p>
          </header>
          <section className='zyco-flange__panel' aria-labelledby='flange-what'><h2 className='zyco-flange__section-title' id='flange-what'>{page.what.title}</h2><p className='zyco-flange__copy'>{page.what.text}</p></section>
          <MinimumFlangeDiagram labels={page.diagram} />
          <section className='zyco-flange__panel' aria-labelledby='flange-why'><h2 className='zyco-flange__section-title' id='flange-why'>{page.why.title}</h2><div className='zyco-flange__cards'>{page.why.cards.map(([title, text]) => <Card key={title} title={title} text={text} />)}</div></section>
          <div className='zyco-flange__grid'>{page.sections.map(([id, title, text]) => <section className='zyco-flange__panel' aria-labelledby={`flange-${id}`} key={id}><h2 className='zyco-flange__section-title' id={`flange-${id}`}>{title}</h2><p className='zyco-flange__copy'>{text}</p></section>)}</div>
          <section className='zyco-flange__panel' aria-labelledby='flange-material'><h2 className='zyco-flange__section-title' id='flange-material'>{page.materials.title}</h2><div className='zyco-flange__cards'>{page.materials.cards.map(([title, text]) => <Card key={title} title={title} text={text} />)}</div></section>
          <section className='zyco-flange__panel' aria-labelledby='flange-chart'><h2 className='zyco-flange__section-title' id='flange-chart'>{page.chart.title}</h2><p className='zyco-flange__copy'>{page.chart.intro}</p><div className='zyco-flange__table-wrap'><table className='zyco-flange__table'><thead><tr>{page.chart.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{page.chart.rows.map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><p className='zyco-flange__reference'>{page.chart.note}</p></section>
          <section className='zyco-flange__panel' aria-labelledby='flange-problems'><h2 className='zyco-flange__section-title' id='flange-problems'>{page.problems.title}</h2><div className='zyco-flange__cards'>{page.problems.cards.map(([title, text]) => <Card key={title} title={title} text={text} />)}</div></section>
          <div className='zyco-flange__grid'>
            <section className='zyco-flange__panel' aria-labelledby='flange-solutions'><h2 className='zyco-flange__section-title' id='flange-solutions'>{page.solutions.title}</h2><p className='zyco-flange__copy'>{page.solutions.intro}</p><ul className='zyco-flange__list'>{page.solutions.items.map((item) => <li className='zyco-flange__copy' key={item}>{item}</li>)}</ul></section>
            <section className='zyco-flange__panel' aria-labelledby='flange-notes'><h2 className='zyco-flange__section-title' id='flange-notes'>{page.notes.title}</h2><ul className='zyco-flange__list'>{page.notes.items.map((item) => <li className='zyco-flange__copy' key={item}>{item}</li>)}</ul></section>
          </div>
          <section className='zyco-flange__panel' aria-labelledby='flange-faq'><h2 className='zyco-flange__section-title' id='flange-faq'>{page.faqTitle}</h2><div className='zyco-flange__faq'>{page.faq.map(([question, answer]) => <article key={question}><h3>{question}</h3><p className='zyco-flange__copy'>{answer}</p></article>)}</div></section>
          <section className='zyco-flange__panel' aria-labelledby='flange-related'><h2 className='zyco-flange__section-title' id='flange-related'>{page.relatedTitle}</h2><nav className='zyco-flange__tools' aria-label={page.relatedAria}>{relatedTools.map(([key, href]) => <a className='zyco-flange__tool' href={href} key={key}>{page.relatedLabels[key] || sharedText.relatedTools[key]}</a>)}</nav></section>
        </div>
      </main>
    </>
  )
}
